

Delete from BillingDepartments
Delete from BillingRateTypes
Insert into BillingDepartments(Id,HospitalId,name) values(1,1,'Service charges')
Insert into BillingDepartments(Id,HospitalId,name) values(2,1,'Delivery charges')
Insert into BillingDepartments(Id,HospitalId,name) values(3,1,'M.I.C.U. charges')
Insert into BillingDepartments(Id,HospitalId,name) values(4,1,'CARDIAC  I.C.U. charges')
Insert into BillingDepartments(Id,HospitalId,name) values(5,1,'S.I.C.U. charges')
Insert into BillingDepartments(Id,HospitalId,name) values(6,1,'LABOUR ROOM  charges')
Insert into BillingDepartments(Id,HospitalId,name) values(7,1,'N.I.C.U.  charges')
Insert into BillingDepartments(Id,HospitalId,name) values(8,1,'MORTUARY  charges')
Insert into BillingDepartments(Id,HospitalId,name) values(9,1,'AMBULANCE charges')
Insert into BillingDepartments(Id,HospitalId,name) values(10,1,'Ventilator charges')
Insert into BillingDepartments(Id,HospitalId,name) values(11,1,'X-RAY  PRICE  LIST')
Insert into BillingDepartments(Id,HospitalId,name) values(12,1,'ROOM  STRUCTURE  & TARIFFS')

select * from BillingRateTypes
Insert into BillingRateTypes values(1,'Flat')
Insert into BillingRateTypes values(2,'Per day')
Insert into BillingRateTypes values(3,'Per hour')
Insert into BillingRateTypes values(4,'Stepwise')

Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'A.R.M.',1,20)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Air Bed',1,100)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Air Bed own',1,50)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Ambubag',1,50)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Ascetic Tapping',1,25)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Ascetic Tapping(Doctor)',1,200)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Asthalin Nebulisation ',1,25)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Binder',1,115)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Biomedical Waste Management charge',1,15)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Bladder Wash',1,20)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Blood Transfusion Charge',1,100)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Bowel Wash',1,30)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'C.P.R.',1,50)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Cannula (Adult)',1,20)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Cannula (Children)',1,25)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Cardiology Consultation 1st Time',1,250)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Cardiology Consultation 2nd visit onwards- op',1,150)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Casualty Consultation ',1,80)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Casualty Consultation Specialist ',1,100)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Casualty Consultation Specialist Night',1,150)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Catgut',1,40)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Consultations – Skin Specialist (per visit) OP',1,100)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Consultations – Gastroenterologist  (first visit)',1,250)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Cathetrisation ',1,40)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Cathetrisation  (Doctor)',1,50)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Colon Wash',1,30)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Colostomy Care',1,75/150)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Combimist Nebulisation ',1,10)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Cotton',1,40)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'CTG charge / Monitoring ',1,150)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'D C Shock',1,50)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Death care',1,250)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Death care  (outside) ',1,350)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Diet per day (ICCU & MICU)',1,100)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Diet per day (Labour Room & Surgical ICU)',1,30)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Discharge Summary card ',1,50)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Doctors Charge(I P)',1,150)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Dress change',1,10)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'ECG  (IP)',1,120)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'ECG  (OP)',1,120)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Echo',1,850)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Endoscopy ( O G D scopy)',1,1000)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'F.T.N.D. Normal Delivery',1,1200)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'F.T.N.D. Vacuum ',1,1300)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Glycerin Enema ',1,30)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Gastrostemic Care',1,50)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'I.M. Injection(IP)',1,2)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'I.M. Injection(OP)',1,5)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'I.R.',1,20)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'I.V. Injection(IP)',1,3)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'I.V. Injection(OP)',1,5)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Immunization Health card',1,50)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Inhalation',1,15)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Inj. Streptokinase – Doctors charge',1,400)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Medicine Bag (Big & medium)',1,10)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Medicine Bag (Small)',1,5)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'New Born Baby Doctors charge  # Ac Room- 125',1,50)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'New Born Baby Nursing care     # Ac Room- 1125',1,40)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Nursing Care',1,130)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'OP Consulting Fees per day',1,80)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'OP Registration Fees',1,50)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Oxygen',1,60)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'P.R.',1,30)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'P.V.Exam',1,20)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Perennial Care',1,15)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Phototherapy alone Double Surface',1,50)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Phototherapy alone Single Surface ',1,40)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Physiotherapy (I.P.)',1,200)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Procalys Enema',1,40)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Ryles tube Aspiration ',1,20)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Scanning',1,450)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Sitz Bath',1,15)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Skin traction 1st day',1,50)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Skin traction 2nd day onwards',1,30)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Soap & Water Enema',1,30)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Speculum Exam',1,20)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'SPO2 per Monitoring',1,30)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'SPO2 per Monitoring / hour',1,50)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Steam Inhalation',1,20)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Sterile Preparation',1,40)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Stomach Wash Adult',1,80)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Stomach Wash Children',1,50)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Surgical, Local, Skin  Preparation',1,40)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Throat Suctioning ',1,20)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'TMT',1,850)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Tracheostomy Care',1,80)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Urine Sugar Testing Ward',1,10)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Vaginal Douche',1,50)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Water Bed per day',1,50)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Water Bed own per day',1,10)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Warmer care',1,40)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Ryles tube feeding',1,20)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Biopsy',1,250)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Specialist Ward visit in Night',1,400)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Laundry charges Single Room (for 3 days)',1,10)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Laundry charges AC Room per day ',1,10)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'House keeping charges Single room per day',1,10)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'House keeping charges AC room per day',1,20)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Medical Certificate',1,100)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Insurance form filling',1,100)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Inj. Pethedine & Morphine charge',1,30)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'OP Consultation fees after OP time',1,100)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'MLC Charge',1,250)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Dental  consultation          ',1,100)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Cardiology package 1',1,900)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Cardiology package 2',1,2800)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Cardiology package 2(without scanning)',1,2600)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'E C G (Rhythem) I P',1,115)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'E C G (Rhythem) O P',1,105)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Phone booking – O P Registration',1,20)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Doctor consultation ( proxy)',1,30)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Cross consultation fees',1,80)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Nurologist consultation(second visit onwards o p)',1,150)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Dopler study (gynaec)',1,20)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'O P Card with bar code',1,10)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Nasal packing',1,50)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'NST/hour (If more than 2 hours)',1,75)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Dental proceed. Charge  -  According to treatment',1,0)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Casualty consultation fees -night',1,100)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'P O P –charges ,slab, others etc',1,0)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Diabetic package',1,1100)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Dressing',1,0)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'I & D',1,100)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'FNAC  (casualty)',1,100)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Dietitians fees(o p)',1,80)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Electricity charges for extra equipments',1,0)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Disposable gowns, mats, baby kit etc',1,0)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Express track',1,100)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Dietitians fees( ip)',1,60)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Nurologist consultation- First visit',1,250)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Delivery Package  - LSCS /Normal Delivery',1,0)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Baby Kit',1,0)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Mortury Charge- Normal',1,700)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Mortury Charge- Glass    ',1,800)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Nurologist consultation – night(casualty)',1,250)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Gastroenterologist (second visit onwards o p)',1,150)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Speech Therapy & Audiology – consultation fees',1,150)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Speech Therapy',1,125)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Hearing screening( OAE)',1,220)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Consultation -specialists second visit onwards - IP',1,200)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Cardiologist Consultation Night',1,500)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'c-pap (per hour)',1,80)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Syringe pump (less than 6 hours) per hour',1,30)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Syringe pump (more than 6 hours) per hour',1,20)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Halter monitoring per day',1,1500)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Vascular Doppler study',1,700)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Biothesiometry',1,400)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Infrared thermometry',1,200)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Duiabetic asessment tests(dopler,biothesi,I R,foot )',1,1300)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Foot pressure mapping',1,200)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Nephrologist consultation(MQMH dialysis patients)',1,50)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Dialysis',1,700)
Insert into BillingCategories(HospitalId,BillingDepartmentId,Name,BillingRateTypeId,ChargePerUnit) values(1,1,'Diet consultation( I P)',1,100)
