//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domains.Billing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BillingCategory()
        {
            this.PatientVisitCosts = new HashSet<PatientVisitCost>();
        }
    
        public int Id { get; set; }
        public int HospitalId { get; set; }
        public int BillingDepartmentId { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> ChargePerUnit { get; set; }
        public int BillingRateTypeId { get; set; }
        public Nullable<int> ChargeUpperBound { get; set; }
        public Nullable<decimal> ChargeAfterUpperBound { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientVisitCost> PatientVisitCosts { get; set; }
        public virtual BillingDepartment BillingDepartment { get; set; }
        public virtual BillingRateType BillingRateType1 { get; set; }
        public virtual Hospital Hospital { get; set; }
    }
}
