//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domains.Billing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientVisitCost
    {
        public int Id { get; set; }
        public int PatientVisitId { get; set; }
        public int BillingCategoryId { get; set; }
        public int Quantity { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int ChargableUnits { get; set; }
    
        public virtual PatientVisit PatientVisit { get; set; }
        public virtual BillingCategory BillingCategory { get; set; }
    }
}
